# Generated by Django 5.1.6 on 2025-02-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('repo_name', models.CharField(max_length=200)),
                ('file_path', models.TextField()),
                ('last_generated_code', models.TextField(blank=True, null=True)),
                ('conversation', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('username', 'repo_name', 'file_path')},
            },
        ),
    ]
