# Generated by Django 5.1.6 on 2025-02-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_codegen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filechat',
            name='file_path',
            field=models.CharField(max_length=2000),
        ),
    ]
