# Generated by Django 5.1.6 on 2025-03-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filechat',
            name='file_path',
            field=models.CharField(max_length=255),
        ),
    ]
